Sync 2021-8-24 (#7)
* feat(route): add 雪球股票评论 (#7822)

* chore(core): Docker build 缩小 image size 更新github action (#7197)

* feat(route): add MacWk (#7833)

* style: auto format

* feat(radar): add radar rules for netease cloud music (mobile) (#7892)

* feat(route): add 生物探索 (#7897)

* fix(route): thu-career (#7894)

Co-authored-by: SettingDust <settingdust@gmail.com>

* style: auto format

* feat(route): 恩山无线论坛板块 (#7365)

Co-authored-by: NeverBehave <gayhub@never.pet>

* feat(route): add x410 news (#7339)

Co-authored-by: NeverBehave <gayhub@never.pet>

* fix(route): 风之动漫域名更换 (#7828)

* fix(route): 紫竹张先生 (#7890)

* fix(docs): HKEPC doc (#7776)

* feat(route): add Fermilab News (#7371)

Co-authored-by: NeverBehave <gayhub@never.pet>

* style: auto format

* fix(route): agefans domain (#7640)

* feat(route): add 湖北软协，武汉东湖高新，武汉科技局 (#7728)

Co-authored-by: long.ye <yelong@orientalmind.com>
Co-authored-by: NeverBehave <gayhub@never.pet>

* style: auto format

* feat(route): add 时事一点通资讯 (#7462)

Co-authored-by: NeverBehave <gayhub@never.pet>

* fix(route): 動畫瘋最後更新 (#7917)

* style: auto format

* fix(pkg): fix use rsshub as package (#7921)

* fix(route): 腾讯较真查证平台 (#7934)

* fix(route): 修复 Bilibili 频道链接，并支持 ctype=1 (#7913)

* feat(route): 中国纺织经济信息网资讯 (#7213)

Co-authored-by: NeverBehave <gayhub@never.pet>

* fix(route): 1X Gallery (#7923)

* feat(route): add World Happiness Report (#7223)

Co-authored-by: NeverBehave <gayhub@never.pet>

* feat(route): add Europa Press (#7943)

Co-authored-by: NeverBehave <gayhub@never.pet>

* fix(route): 修复 soul 请求链接 (#7955)

* fix(core): make sure timeout error messages include URLs (#7981)

Before this fix, timeout messages are not quite useful

> error: Request undefined fail, retry attempt #1: TimeoutError: Timeout awaiting 'request' for 5000ms

* feat(route): add 西北农林科技大学 (#7966)

* feat(route): add Sky Sports News (#7968)

Co-authored-by: Sukka <isukkaw@gmail.com>
Co-authored-by: NeverBehave <gayhub@never.pet>

* feat(route): add Common App blog (#7287)

Co-authored-by: NeverBehave <gayhub@never.pet>

* feat(route): japanpost improve timezone parse (#7682)

* feat(route): add 财新数据通专享资讯 (#7250)

* feat(route): add 游迅网资讯 (#7235)

* feat(route): add The Partnership on AI Resources (#7265)

Co-authored-by: NeverBehave <gayhub@never.pet>

* fix(route): 重庆大学本科教学信息网 (原重庆大学教务网) (#7944)

* feat(route): add 掘金专栏 (#7889)

* feat(route): add 掘金专栏

* fix: 时间处理

* feat(route): add 温州大学新闻 (#7952)

Co-authored-by: NeverBehave <gayhub@never.pet>

* feat(route): add yuzu emulator blog (#7947)

Co-authored-by: NeverBehave <gayhub@never.pet>

* style: auto format

* chore(misc): fix various ci issue

*some of them shown cancelled instead of failed. Need to address this issue later

* chore(misc): bump to node 14, simplify template

* docs(install): README.md (#7994)

heroku补充描述
heroku additional description
vercel 补充描述
vercel additional description

* style: auto format

* chore(dockerfile): bump builder image

* docs(install): README.md (#7994)

heroku补充描述
heroku additional description
vercel 补充描述
vercel additional description

* style: auto format

* fix(dockerfile): copy necessary file when building (#8008)

* fix(dockerfile): copy necessary file when building

*when even bother deleting file...

* no console

* style: auto format

* chore(test): test running docker after build (#8010)

* chore(test): test running docker after build

* add test in the same step

* add count times

* workflow typo

* add name when output

* if then

* test docker

* use id

* no tag

* what is docker id

* load single platform

* do not test multi-arch for now

* no load

* fix(route): 修复 bilibili 动态无法获取问题 (#7961)

* feat(route): load route handler on the first request (#8021)

* refactor: avoid promise overhead (#8028)

* style/chore(eslint): enforce new rules (#8040)

* style: prefer object shorthand syntax
* refactor: prefer Array#map over Array#forEach
* style: prefer arrow callback
* chore(eslint): update rules
* style: auto fix by eslint

* fix(route): 站酷发现有视频条目 (#8044)

* fix(zimuxia-portfollo): `$.reverse` is removed (#8047)

* feat(route): add hket (#8050)

* perf: lazy require dependencies (#8025)

* style: auto format

* fix(route): hket Missing `url` property (#8052)

* feat(route): add Font Story (DynaC TW) (#7565)

* style: auto format

* docs(install): add heroku usage limit notice (#8060)

add English notice about heroku

* docs(install): remove vercel timeout notice (#8060) (#8059)

Co-authored-by: zytomorrow <z794672847@gmail.com>
Co-authored-by: fengkx <liangkx8237@gmail.com>
Co-authored-by: VJ <i.am.f48vj+github@gmail.com>
Co-authored-by: GitHub Action <action@github.com>
Co-authored-by: cayZ <13341339+Cay-Zhang@users.noreply.github.com>
Co-authored-by: Aidi Stan <aidistan@live.com>
Co-authored-by: DylanXie123 <dylanxie123@outlook.com>
Co-authored-by: SettingDust <settingdust@gmail.com>
Co-authored-by: Ethan Shen <nczitzk@gmail.com>
Co-authored-by: NeverBehave <gayhub@never.pet>
Co-authored-by: Tony <TonyRL@users.noreply.github.com>
Co-authored-by: Colerar <62297254+Colerar@users.noreply.github.com>
Co-authored-by: tudou027 <future2100@163.com>
Co-authored-by: long.ye <yelong@orientalmind.com>
Co-authored-by: auto-bot-ty <75887908+auto-bot-ty@users.noreply.github.com>
Co-authored-by: 神楽坂みずき <45122329+cokemine@users.noreply.github.com>
Co-authored-by: Raidou <weirongxu.raidou@gmail.com>
Co-authored-by: BugWriter2 <frank16874@outlook.com>
Co-authored-by: Chih-Hsuan Yen <yan12125@gmail.com>
Co-authored-by: Ding Yuxiao <yuxiaoding@acm.org>
Co-authored-by: Sukka <isukkaw@gmail.com>
Co-authored-by: tuzi3040 <28290621+tuzi3040@users.noreply.github.com>
Co-authored-by: Hagb (Guo Junyu 郭俊余) <hagb_green@qq.com>
Co-authored-by: 向 <xiangzy8@gmail.com>
Co-authored-by: yesRabbit <trlu.develop@outlook.com>
Co-authored-by: D <48525679+ding667@users.noreply.github.com>
Co-authored-by: zsh2517 <30528671+zsh2517@users.noreply.github.com>
Co-authored-by: Trim21 <trim21.me@gmail.com>
Co-authored-by: Toby Tso <7851076+tpnonthealps@users.noreply.github.com>